# Generated by Django 5.2.7 on 2025-10-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='UTEPPI', max_length=200)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tiempo_sesion', models.IntegerField(default=60, help_text='Minutos de inactividad para cerrar sesión')),
                ('mantenimiento', models.BooleanField(default=False, help_text='Activar modo mantenimiento')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
