# Generated by Django 5.2.7 on 2026-02-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('oficial_administrativo', 'Oficial Administrativo'), ('usuario_autorizado', 'Usuario Autorizado')], default='usuario_autorizado', help_text='Define el nivel de acceso del usuario en el sistema', max_length=25),
        ),
    ]
