# Generated by Django 5.2.7 on 2026-02-06 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_rol'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='personal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_acceso', to='personal.personalpolicial', verbose_name='Personal vinculado'),
        ),
    ]
