# Generated by Django 5.2.7 on 2026-06-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('oficial_administrativo', 'Oficial Administrativo'), ('usuario_autorizado', 'Usuario Autorizado'), ('temporal', 'Usuario Temporal')], default='usuario_autorizado', help_text='Define el nivel de acceso del usuario en el sistema', max_length=25),
        ),
    ]
