# Generated by Django 5.2.7 on 2026-10-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('personal', '0004_alter_destinopolicial_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='comandante',
            field=models.ForeignKey(blank=True, help_text='Personal designado como comandante de esta unidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_comandadas', to='personal.personalpolicial'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en los reportes')),
                ('activo', models.BooleanField(default=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='catalogos.unidad')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['unidad', 'orden'],
            },
        ),
    ]
