# Generated by Django 5.2.7 on 2026-10-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_unidad_ciudad_unidad_comandante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestado',
            name='cumple_funciones',
            field=models.BooleanField(default=True, help_text='Desmarcar para estados como Retiro Temporal, Comisión, Baja Definitiva, Fallecido, etc.', verbose_name='¿Cumple funciones en la unidad?'),
        ),
    ]
