# Generated by Django 5.2.7 on 2026-10-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_tipoestado_cumple_funciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='abreviatura',
            field=models.CharField(max_length=15),
        ),
    ]
