# Generated by Django 5.2.7 on 2026-03-17 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', '🔐 Inicio de sesión'), ('LOGOUT', '🚪 Cierre de sesión'), ('CREAR', '➕ Crear'), ('EDITAR', '✏️ Editar'), ('ELIMINAR', '🗑️ Eliminar'), ('VER', '👁️ Ver'), ('ERROR', '❌ Error'), ('OTRO', '⚙️ Otro')], max_length=20, verbose_name='Acción')),
                ('modulo', models.CharField(choices=[('personal', 'Personal'), ('destinos', 'Destinos'), ('catalogos', 'Catálogos'), ('permisos', 'Permisos'), ('sanciones', 'Sanciones'), ('felicitaciones', 'Felicitaciones'), ('kardex', 'Kardex'), ('usuarios', 'Usuarios'), ('reportes', 'Reportes'), ('sistema', 'Sistema')], default='sistema', max_length=30, verbose_name='Módulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del objeto')),
                ('objeto_repr', models.CharField(blank=True, max_length=300, null=True, verbose_name='Objeto afectado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de bitácora',
                'verbose_name_plural': 'Bitácora / Logs',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
