# Generated by Django 5.2.7 on 2025-10-25 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificacion', models.CharField(max_length=20, unique=True)),
                ('ci', models.CharField(max_length=15, unique=True)),
                ('expedido', models.CharField(default='LP', max_length=5)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_ingreso', models.DateField()),
                ('telefono_personal', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personal/fotos/')),
                ('qr_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipoestado')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.grado')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.unidad')),
            ],
            options={
                'verbose_name': 'Personal Policial',
                'verbose_name_plural': 'Personal Policial',
                'ordering': ['grado__orden', 'apellido_paterno'],
            },
        ),
        migrations.CreateModel(
            name='PermisoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permiso', models.CharField(choices=[('administrativo', 'Permiso Administrativo'), ('medico', 'Permiso Médico'), ('personal', 'Permiso Personal'), ('comision', 'Comisión de Servicio'), ('vacaciones', 'Vacaciones')], max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.IntegerField(editable=False)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, null=True)),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='permisos/documentos/')),
                ('numero_oficio', models.CharField(blank=True, max_length=50, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='personal.personalpolicial')),
            ],
            options={
                'verbose_name': 'Permiso o Licencia',
                'verbose_name_plural': 'Permisos y Licencias',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='KardexDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(choices=[('ingreso', 'Ingreso a la Institución'), ('ascenso', 'Ascenso de Grado'), ('traslado', 'Traslado de Unidad'), ('estado', 'Cambio de Estado'), ('sancion', 'Sanción Aplicada'), ('felicitacion', 'Felicitación'), ('permiso', 'Permiso o Licencia'), ('otro', 'Otro')], max_length=15)),
                ('fecha_registro', models.DateField()),
                ('descripcion', models.TextField()),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_anterior', to='catalogos.tipoestado')),
                ('estado_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_nuevo', to='catalogos.tipoestado')),
                ('grado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_anterior', to='catalogos.grado')),
                ('grado_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_nuevo', to='catalogos.grado')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidad_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_anterior', to='catalogos.unidad')),
                ('unidad_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_nuevo', to='catalogos.unidad')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='personal.personalpolicial')),
            ],
            options={
                'verbose_name': 'Registro de Kardex',
                'verbose_name_plural': 'Registros de Kardex',
                'ordering': ['-fecha_registro', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FelicitacionAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_felicitacion', models.DateField()),
                ('motivo', models.TextField()),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_felicitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipofelicitacion')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='felicitaciones_aplicadas', to='personal.personalpolicial')),
            ],
            options={
                'verbose_name': 'Felicitación Aplicada',
                'verbose_name_plural': 'Felicitaciones Aplicadas',
                'ordering': ['-fecha_felicitacion'],
            },
        ),
        migrations.CreateModel(
            name='SancionAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sancion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cumplida', 'Cumplida'), ('anulada', 'Anulada')], default='activa', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_aplicadas', to='personal.personalpolicial')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_sancion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tiposancion')),
            ],
            options={
                'verbose_name': 'Sanción Aplicada',
                'verbose_name_plural': 'Sanciones Aplicadas',
                'ordering': ['-fecha_sancion'],
            },
        ),
    ]
