# Generated by Django 5.2.7 on 2026-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_personal_campos_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinopolicial',
            name='descripcion',
            field=models.TextField(help_text='Motivo o detalle del destino'),
        ),
        migrations.AlterField(
            model_name='destinopolicial',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar vacío si es indefinido', null=True),
        ),
        migrations.AlterField(
            model_name='destinopolicial',
            name='lugar_destino',
            field=models.CharField(help_text='Ciudad, departamento o lugar específico', max_length=200),
        ),
        migrations.AlterField(
            model_name='destinopolicial',
            name='numero_resolucion',
            field=models.CharField(blank=True, help_text='N° de resolución o documento', max_length=100, null=True),
        ),
    ]
