# Generated by Django 5.2.7 on 2026-10-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_unidad_ciudad_unidad_comandante_and_more'),
        ('personal', '0004_alter_destinopolicial_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalpolicial',
            name='cargo_actual',
        ),
        migrations.AddField(
            model_name='personalpolicial',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_asignado', to='catalogos.cargo', verbose_name='Cargo actual'),
        ),
    ]
