# Generated by Django 5.2.7 on 2026-10-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_personalpolicial_cargo_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalpolicial',
            name='tipo_carrera',
            field=models.CharField(choices=[('carrera', 'De Carrera'), ('servicio', 'De Servicio')], default='carrera', max_length=10, verbose_name='Tipo de Personal'),
        ),
    ]
