# Generated by Django 5.2.7 on 2026-10-04 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_personalpolicial_tipo_carrera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_baja', models.CharField(choices=[('baja_definitiva', 'Baja Definitiva de la Institución'), ('retiro_temporal', 'Retiro Temporal (Cat. B)'), ('licencia_indefinida', 'Licencia Indefinida')], max_length=20)),
                ('fecha_baja', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('resolucion_tds', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resolución TDS')),
                ('numero_memo_escalafon', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Memo. Escalafón')),
                ('autoridad_firma', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad que firma')),
                ('cargo_autoridad_firma', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo de la autoridad')),
                ('fecha_notificacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baja', to='personal.personalpolicial')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baja de Personal',
                'verbose_name_plural': 'Bajas de Personal',
            },
        ),
        migrations.CreateModel(
            name='Fallecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fallecimiento', models.DateField()),
                ('causa_deceso', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_certificado_defuncion', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Certificado de Defunción')),
                ('entidad', models.CharField(blank=True, help_text='Entidad que emite el certificado', max_length=200, null=True)),
                ('autoridad_firma', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad que firma')),
                ('numero_informe_trabajo_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Informe de Trabajo Social')),
                ('fecha_informe', models.DateField(blank=True, null=True)),
                ('direccion_departamental_salud', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dir. Dptal. Salud que remite')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fallecimiento', to='personal.personalpolicial')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fallecimiento',
                'verbose_name_plural': 'Fallecimientos',
            },
        ),
    ]
